name: Build and deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    concurrency:
      group: "${{ github.ref_name }}"
      cancel-in-progress: true
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install and configure the Koyeb CLI
        uses: koyeb-community/koyeb-actions@v2
        with:
          api_token: "${{ secrets.KOYEB_API_TOKEN }}"

      - name: Build and deploy the application to Koyeb
        uses: koyeb/action-git-deploy@v1
        with:
          service-env: ASTRA_TOKEN=@ASTRA_TOKEN,ASTRA_DATABASE=@ASTRA_DATABASE,ASTRA_COLLECTION=@ASTRA_COLLECTION,API_BASE_URL=@API_BASE_URL
          service-instance-type: free
          service-ports: "8080:http"
          service-routes: "/:8080"
          service-checks: "8080:http:/"
          git-builder: docker